---
####################################################################################
#  This playbook only builds the docker images locally
#
####################################################################################



  - name: "Extract DIST from Unfetter UI"
    command: "{{ item }}"
    with_items:
    - docker run --rm -v {{ role_path }}/files/ui-dist/prod-ff31:/usr/share/unfetter-ui/dist --name unfetter-ui-build-temp unfetter-ui:{{docker_tag}} npm run build:prod:noclean:ff31
    - docker run --rm -v {{ role_path }}/files/ui-dist/demo-ff31:/usr/share/unfetter-ui/dist --name unfetter-ui-build-temp unfetter-ui:{{docker_tag}} npm run build:demo:noclean:ff31
    - docker run --rm -v {{ role_path }}/files/ui-dist/prod:/usr/share/unfetter-ui/dist --name unfetter-ui-build-temp unfetter-ui:{{docker_tag}} npm run build:prod:noclean
    - docker run --rm -v {{ role_path }}/files/ui-dist/demo:/usr/share/unfetter-ui/dist --name unfetter-ui-build-temp unfetter-ui:{{docker_tag}} npm run build:demo:noclean

  - name: "Create {{ image_name }}.{{ item }}"
    docker_image:
      name: "{{ image_name }}.{{ item }}"
      state: present
      path: "{{ role_path }}/files"
      dockerfile: "/Dockerfile.{{ item }}"
    with_items:
      - "demo"
      - "legacy.demo"
      - "legacy.uac"
      - "uac"
